Update system-testing.yml

diff --git a/.github/workflows/system-testing.yml b/.github/workflows/system-testing.yml
--- a/.github/workflows/system-testing.yml
+++ b/.github/workflows/system-testing.yml
@@ -11,7 +11,23 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Trigger Repository Dispatch
+        env:
+          LOCATION: echo -e "${{ github.event.pull_request.body }}" | grep "^DEPENDS ON" | sed 's/DEPENDS ON //'
         run: |
+          STATUS=$(curl -o /dev/null -s -w "%{http_code}" "$LOCATION")
+          if [[ "$STATUS" -eq 200 ]]; then
+            echo "repository found"
+          else
+            echo "repository not found"
+            exit 1
+          fi
+          D_REPO=$(echo -e $LOCATION | awk -F "/" '{print $4 "/" $5}')
+          D_BRANCH=$(echo -e $LOCATION | awk -F "/tree/" '{print $2}')
+          if [[ -z "$D_BRANCH" ]]; then
+            echo "branch collected"
+          else
+            echo "missing branch, if the branch is master, please don't specify the keyword DEPENDS ON at the beginning of line"
+          fi
           echo ${{ secrets.ADMIN }}
           curl -X POST \
           -H "Authorization: token ${{ secrets.ADMIN }}" \
@@ -20,9 +36,11 @@ jobs:
           -d '{
             "event_type": "cross-repo-test",
             "client_payload": {
-              "repository": "${{ github.repository }}",
-              "branch": "${{ github.event.pull_request.head.ref }}",
-              "pull_request_url": "${{ github.event.pull_request.html_url }}"
+              "repository_A": "${{ github.repository }}",
+              "branch_A": "${{ github.event.pull_request.head.ref }}",
+              "pull_request_url_A": "${{ github.event.pull_request.html_url }}"
+              "repository_B": "$D_REPO",
+              "branch_B": "$D_BRANCH"
             }
           }' \
           https://api.github.com/repos/sluFicodes/DOME-testing/dispatches
