update workflow

diff --git a/.github/workflows/system-testing.yml b/.github/workflows/system-testing.yml
--- a/.github/workflows/system-testing.yml
+++ b/.github/workflows/system-testing.yml
@@ -23,13 +23,19 @@ jobs:
             exit 1
           fi
           TM_VERSION=$(echo -e '${{ github.event.pull_request.body }}' | grep '^TM_VERSION' | sed 's/TM_VERSION //')
-          echo tmforum api version: $TM_VERSION
+          if [[ -z "$TM_VERSION" ]]; then
+            echo "tmforum api version: $TM_VERSION"
+          else
+            echo "missing tmforum api version"
+            exit 1
+          fi
           D_REPO=$(echo -e $LOCATION | awk -F "/" '{print $4 "/" $5}')
           D_BRANCH=$(echo -e $LOCATION | awk -F "/tree/" '{print $2}')
           if [[ -z "$D_BRANCH" ]]; then
             echo "branch collected: $D_BRANCH"
           else
             echo "missing branch, if the branch is master, please don't specify the keyword DEPENDS ON at the beginning of line"
+            exit 1
           fi
           echo ${{ secrets.ADMIN }}
           curl -X POST \
